/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import googleMaps from "@amicaldo/strapi-google-maps/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiContentTypeExplorer from "strapi-content-type-explorer/strapi-admin";
import entityRelationshipChart from "strapi-plugin-entity-relationship-chart/strapi-admin";
import pagepreview from "strapi-plugin-website-preview/strapi-admin";
import modelsRelationDiagram from "strapi4-models-relation-diagram/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "google-maps": googleMaps,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-content-type-explorer": strapiContentTypeExplorer,
    "entity-relationship-chart": entityRelationshipChart,
    pagepreview: pagepreview,
    "models-relation-diagram": modelsRelationDiagram,
  },
});
